# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-26 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PlanLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_created=True)),
                ('line_id', models.CharField(max_length=256)),
                ('start_point', models.CharField(max_length=256)),
                ('start_longitude', models.CharField(max_length=256)),
                ('start_latitude', models.CharField(max_length=256)),
                ('end_point', models.CharField(max_length=256)),
                ('end_longitude', models.CharField(max_length=256)),
                ('end_latitude', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_created=True)),
                ('point_id', models.CharField(max_length=256)),
                ('longitude', models.CharField(max_length=256)),
                ('latitude', models.CharField(max_length=256)),
                ('altitude', models.CharField(max_length=256)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.PlanLine')),
            ],
        ),
        migrations.CreateModel(
            name='RealPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_created=True)),
                ('real_id', models.CharField(max_length=256)),
                ('real_longitude', models.CharField(max_length=256)),
                ('real_latitude', models.CharField(max_length=256)),
                ('real_altitude', models.CharField(max_length=256)),
                ('real_hs', models.CharField(max_length=256)),
                ('real_vs', models.CharField(max_length=256)),
                ('real_count', models.CharField(max_length=256)),
                ('real_battery', models.CharField(max_length=256)),
                ('real_roll', models.CharField(max_length=256)),
                ('real_pitch', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_created=True)),
                ('uav_id', models.CharField(max_length=256)),
                ('uav_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UavData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_created=True)),
                ('sortie_py', models.CharField(max_length=256)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.PlanLine')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Uav')),
            ],
        ),
        migrations.CreateModel(
            name='UavType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_created=True)),
                ('uav_model', models.CharField(max_length=256)),
                ('uav_type', models.CharField(max_length=256)),
                ('uav_weight', models.CharField(max_length=256)),
                ('uav_norm_weight', models.CharField(max_length=256)),
                ('uav_max_weight', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UavUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('nickname', models.CharField(max_length=256, verbose_name='昵称')),
                ('hash_password', models.CharField(max_length=256, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uav_user', to='map.Permission', verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='uav',
            name='uav_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.UavUser'),
        ),
        migrations.AddField(
            model_name='uav',
            name='uav_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.UavType'),
        ),
        migrations.AddField(
            model_name='realpoint',
            name='sortie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_point', to='map.UavData'),
        ),
        migrations.AddField(
            model_name='realpoint',
            name='uav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Uav'),
        ),
    ]
