# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180626_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realpoint',
            name='sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_point', to='map.UavData'),
        ),
    ]
