# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20180629_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realpoint',
            name='sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.UavData'),
        ),
    ]
