# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-28 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20181027_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='uavdata',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '选中'), (2, '已完成')], default=1, verbose_name='状态'),
        ),
    ]
