# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-26 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181025_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=16, verbose_name='地址'),
        ),
    ]
