# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_uav_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '在线'), (2, '离线'), (3, '维修')], default=2, verbose_name='状态'),
        ),
    ]
